### ISSUE TITLE
Myst returns an `Invalid DOI` error, even if the DOI is correct

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [executablebooks/mystmd#1074]
Hello, and thanks for myst, it's great! 

I'm currently using myst v1.1.50, and the following (valid) DOI results in a `DOI is not valid` error: 

https://doi.org/10.1002/(SICI)1096-987X(199709)18:12%3C1450::AID-JCC3%3E3.0.CO;2-I

## Description

Upon saving the file myst returns the following error

```
⛔️ enhanced.md:106 DOI is not valid: doi:10.1002/(SICI)1096-987X(199709)18:12%3C1450::AID-JCC3%3E3.0.CO;2-I
```

## Proposed solution

Improve the DOI-parsing bit so that it supports this type of valid (even if weird) DOIs 

## Additional notes

This is the first time it happens to me, and I couldn't find any other non-working example, so it may be a pretty rare occurrence.

**Comment by rowanc1** [comment]
We had a regression around this, the fix is in #1075, and I have tested your URL locally. Thanks for the bug report!

When this works again (should be released in a few days), there are a few notes about complex DOIs in the docs, the best workaround is to use the [`shortdoi`](https://shortdoi.org/) service offered by doi.org directly, these are persistent short links for complex DOIs that are supported for the long-term.

More in the docs here in "dealing with complex DOIs":
https://mystmd.org/guide/citations#doi-links

**Comment by rowanc1** [comment]
There is a separate follow on bug in the renderer:

![image](https://github.com/executablebooks/mystmd/assets/913249/6070c1fe-af47-451a-9139-d2ace008bd01)

This could be cleared up by using the short-doi locally, but will leave it open to track the improvement.

**Comment by lorenzo-rovigatti** [comment]
Thank you so much for your (super quick) response! I updated the page with the shortdoi url, so that it will work as soon as the new version is released.

**Comment by lorenzo-rovigatti** [comment]
The new release (1.1.53) fixes the issue. Thanks a lot!

**Comment by rowanc1** [comment]
Wonderful - glad it is working for you! 🚀
