### ISSUE TITLE
Install MyST CLI using tools Pythonistas are familiar with (e.g. conda)

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#139]
It is possible to install node dependencies through Conda, including activating the correct version of nodejs. @stevejpurves and I tried this a few months back and couldn't figure it out.

If anyone from the community has experience with this, we would absolutely love the help!! I believe that having this in a more familiar package manager would certainly help with onboarding Python users.

@choldgraf maybe you have some pointers on who can do this sort of stuff in their sleep?!

**Comment by choldgraf** [comment]
In my experience - there are many in the conda-forge community who are willing to help maintain packages and who know much more about it than I do :-)   lots of folks help maintain other parts of the myst python ecosystem as well. 

Maybe @ocefpaf has thoughts on anybody that knows how to manage javascripty things in the conda-forge world?

Another option is that I think we *could* actually make mystjs installable with python as well, I know that the sphinx-theme-builder uses nodeenv to bundle its own version of node, and that might be an option ([ref `pyproject.toml`](https://github.com/pradyunsg/sphinx-theme-builder/blob/main/pyproject.toml))...cc @pradyunsg if he has any thoughts there

**Comment by ocefpaf** [comment]
> Maybe @ocefpaf has thoughts on anybody that knows how to manage javascripty things in the conda-forge world?

I don't know the first thing about JS but we do package node on conda-forge and folks use it to later install JS stuff. Maybe @bollwyvl did some recipes with that? Sorry bollwyvl  if I'm misremembering.

**Comment by pradyunsg** [comment]
Is there a reason the CLI was built on the JS toolchain rather than the Python one? But more broadly, we could use nodeenv under the hood of a PyPI package if we really wanted to do that; but it might actually be cleaner to provide a `myst-cli` on PyPI that uses `myst-parser` rather than trying to adapt a npm package to a PyPI package (it works for pyright though, so it's not strictly out of the picture).

**Comment by bollwyvl** [comment]
Some thoughts on packaging and distributing `npm` confections as useful CLI tools:

- use [`ncc`](https://www.npmjs.com/package/@vercel/ncc) single-file distributions
  - nobody wants the 1000s of `node_modules` files crapped all over their env, much less their path length, space, and case (in)sensitivity on windows
- try to get stuff to install with `--ignore-optionals`, `--ignore-scripts`, and anything else that reduces the surface area of drive-by npm modulejacking, etc.
- capture the versions (and full licenses) of the mountain of third-party dependencies that this will inevitably be vendored
- make simple wrappers (e.g. `.bat`, `.sh`, etc) rather than requiring `nodejs path/to/thing.js`
- establish a policy of building (and testing) against the oldest active [node LTS](https://github.com/nodejs/release#release-schedule)
- probably consider alternate, less-insecure js runtimes like `deno` and `bun`

as to the python-node-sandwich:

- if _really_ wanting to do this with python, make a [wrapper script](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/jlpmapp.py) that's good at dealing with nodejs `%PATH%` hell
  - but i really just _can't_ recommend a python package installing a "magic" nodejs environment
    - especially one pinned down to a hard version, which seems to be _en vogue_
- if particularly crazy, it's _possible_ (especially with self-contained scripts) to do run against a v8-in-python like [pyminiracer](https://github.com/sqreen/PyMiniRacer) or [pyduktape2](https://pypi.org/project/pyduktape2)
  - both appear semi-dead, and have lingering licensing issues because v8

**Comment by rowanc1** [comment]
This is fantastic -- thank you @bollwyvl!! We are already getting down to a single `js` file with esbuild, I will look into `ncc` as well (not sure what the tradeoffs are). Right now the entire CLI is a single file, that can just run via `node myst.js -v` etc.

For "make [a] simple wrapper", I am still pretty fuzzy here: \
is this what would be packaged up and distributed through pypi or conda (along with licenses)? Do you know any examples in the [conda?] ecosystem that: (1) ensure a version of node is installed (maybe you are saying this is optional / we shouldn't); (2) wrap up that single JS file; and (3) provide access without requiring the `node cli.js`?

Any pointers on that final step would be really helpful - @stevejpurves is also a bit more versed in the python packaging world, and might be able to ask better questions!

**Comment by bollwyvl** [comment]
If distributing through PyPI (a well-understood source for `conda-forge`), it might look something like [this](https://github.com/martinRenou/yaml-lsp/blob/master/yaml_lsp/main.py) with some `entry_point` cruft like [this](https://github.com/martinRenou/yaml-lsp/blob/master/setup.cfg#L27) (stirring in whatever build backend you want).

Then the `conda-forge` package (which would get automated PRs after PyPI releases) would look something like [this](https://github.com/conda-forge/yaml-lsp-feedstock/blob/main/recipe/meta.yaml). This one just says `node`, though i'd, again, suggest pinning to even-numbered LTS `node`s, or having a single feedstock that built `thing` and `thing-base` that doesn't rely on `node` at all... one should _opt into_ beta testing the odd-numbered releases.

Another tack altogether is targeting WASM, which would be portable, as node/deno/bun and the browser would run it natively, while python (and many other languages) could use one of the various bridge backends such as wasmer, etc. There is nascent tooling for doing this from JS with e.g. QuickJS, but it does open the can of worms of porting to rust, which has robust wasm, node, _and_ python toolchains.

**Comment by rowanc1** [comment]
This has now been completed!
https://mystmd.org/guide/quickstart#installing-the-myst-markdown-cli

The CLI is available as mystmd across all package managers! 🚀

Thanks all for your help. :)
