### ISSUE TITLE
SyntaxError: Invalid regular expression: /[\p{Lu}]/: Invalid property name in character class

### ISSUE THREAD

**Issue by agoscinski** [executablebooks/mystmd#594]
## Description
After following the installation instruction (`npm install -g mystmd`). I get the following error
```
$ myst --version

/opt/anaconda3/lib/node_modules/mystmd/dist/myst.cjs:236889
var UPPERCASE = /[\p{Lu}]/u;
                ^^^^^^^^^^^

SyntaxError: Invalid regular expression: /[\p{Lu}]/: Invalid property name in character class
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.15.0
```
I did not see any other requirements other than
```
[Node.js](https://nodejs.org/) version >=16.0.0
[Node Package Manager (npm)](https://docs.npmjs.com/about-npm) version >=7.0.0
```
which I fulfill 
```
$ npm --version
9.5.0
```
Also tried `myst init -d` for additional information, but the output is the same

**Comment by fwkoch** [comment]
Hey @agoscinski - Thanks for submitting this! Turns out it is a very specific issue with conda and that version of node. Take a look here: https://stackoverflow.com/questions/76580828/invalid-property-name-in-character-class-webpack-npm

I was able to recreate your bug by using `node=18.15.0` installed with conda, and sure enough, updating to `node=18.16.1` with conda resolved it. You could also switch to a different node installation; I use  [nvm](https://github.com/nvm-sh/nvm) to manage my node versions and had no problem with `node=18.15.0`.

Closing this for now as there is nothing we can do to fix it... feel free to re-open if the above don't work for you!
