### ISSUE TITLE
Dates OBO

### ISSUE THREAD

**Issue by rkurchin** [executablebooks/mystmd#607]
## Description
In both the Markdown preview within Jupyter Lab and the MyST-rendered website, any date seems to show up as the day before the one I specify. See [my repo](https://github.com/rkurchin/BPE-demo-myst) – I haven't changed anything about the template, just added/tweaked content. Not sure if this reproduces on another system.

## Proposed solution
???

## Additional notes
Versions...
**Myst:** 1.1.15
**OS:** macOS 12.6.8 Monterey
**Node:** 16.13.1

**Comment by rowanc1** [comment]
Thanks @rkurchin for the issue. We are likely parsing in a specific timezone and rendering in a different one (or the opposite). Will track this down!

**Comment by nshahquinn** [comment]
I noticed this as well.

It looks like the specified date is parsed as a UTC datetime. If you do a static HTML build (`myst build --html`), it gets included in the HTML output with a display value based on the system time zone of the building computer (e.g. `2024-02-02` becomes `<time dateTime="2024-02-02T00:00:00.000Z" class="">February 1, 2024</time>` since I'm in the Western hemisphere). If you're running `myst start`, it depends instead on the time zone included with the browser's request.

**Comment by rowanc1** [comment]
Thanks both for your help in tracking this down. The two linked PRs should fix it, and we will get a release out soon!
